language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  - yarn install
script:
  - yarn run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t happyfly/happyfly-info:latest
  - docker push happyfly/happyfly-info:latest
