sudo: required

language: node_js
node_js:
  - stable
services:
  - docker

before_install:
  - yarn install

script:
  - yarn run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t thawsoar/happyfly-info:latest .
  - docker push thawsoar/happyfly-info:latest
